### Send POST request with body as parameters
POST http://localhost:8702/api/books
Content-Type: application/x-www-form-urlencoded

title=My great book&year=2020&author=Art Shyshkin&genre=Fantasy

###
